services:
  flask_app:
    build:
      context: ./services/flask_app
      dockerfile: Dockerfile
    container_name: flask-app
    image:
      flask-app:latest
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
    ports:
      - 5000:5000
    volumes:
      - flask_data:/app/src/instance

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  worker:
    build:
      context: ./services/flask_app
      dockerfile: Dockerfile
    command: "celery --workdir=src -A app.celery_app worker --loglevel=info"
    depends_on:
      - redis
      - flask_app
    environment:
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
    volumes: 
      - flask_data:/app/src/instance

volumes:
  flask_data: {}
  redis_data: {}